{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[2m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[2m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "pods per namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node cpu  usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node)(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^.*$\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^.*$\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods per nodes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info) by (node)", "legendFormat": "__auto" }
   ]
  }
 ]
}