apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argo
spec:
  project: default
  source:
    chart: elasticsearch 
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.5.10
    helm:
      parameters:
        - name: "global.kibanaEnabled"
          value: "true"
      releaseName: elasticsearch
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging

  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - CreateNamespace=true